services:
    gwent-classic:
        container_name: gwent-classic
        build:
        context: .
        ports:
            - "${WEBSOCKET_PORT}:${WEBSOCKET_PORT}"
            - "${WEBSERVER_PORT}:${WEBSERVER_PORT}"
